### ISSUE TITLE
Arch / tune broken on CI builds

### ISSUE THREAD

**Issue by offa** [jhnc-oss/yocto-build#25]
x86_64 builds use the wrong architecture and tune:

```
NOTE: Setting MACHINE to genericx86
NOTE: Setting DEFAULTTUNE to i586
```

**Comment by offa** [comment]
Strange, neither `BB_ENV_EXTRAWHITE` nor `YOCTO_TARGET_ARCH` affect them.

**Comment by h5b** [comment]
> x86_64 builds use the wrong architecture and tune:
> 
> ```
> NOTE: Setting MACHINE to genericx86
> NOTE: Setting DEFAULTTUNE to i586
> ```

dev/bootstrap.sh pushes --env "BB_ENV_EXTRAWHITE=YOCTO_TARGET_ARCH"

**Comment by offa** [comment]
I've noted it on the CI builds today.

**Comment by h5b** [comment]
> I've noted it on the CI builds today. The info message isn't available in early builds unfortunately.
> 
> CI builds don't use the bootstrap script.
Of course not but it is capable of passing the ARCH/tune correctly. Therefore, it seems to be limited to CI environment only.

**Comment by offa** [comment]
That's right.

**Comment by offa** [comment]
`YOCTO_TARGET_ARCH` is `None` for both arch settings!?

**Comment by h5b** [comment]
github actions seem to be pretty picky when it comes to environment passing.

**Comment by offa** [comment]
Yes, but I guess I have have a solution ... stay tuned ...
