### ISSUE TITLE
Parse recipes as part of CI builds

### ISSUE THREAD

**Issue by offa** [jhnc-oss/yocto-build#31]
Parsing of relevant recipes in the CI build. At the moment only one tree is verified.

**Comment by h5b** [comment]
@offa 

While being a cheap shot we might just call
```
bitbake -n world
```

This seems to spot at least issues on recipe/packagegroup level (missing providers due to typo and the likes).

**Comment by h5b** [comment]
Well, after some more thought bitbake -n world seems to be best placed in the nightly regression run.

**Comment by offa** [comment]
Sounds good, even if it's only on a cron build it might catch some mistakes. PR follows ...
