### ISSUE TITLE
Fix uid/gid mapping for non-main branches

### ISSUE THREAD

**Issue by h5b** [jhnc-oss/yocto-build#58]
https://github.com/jhnc-oss/yocto-build/commit/8b70fee62c2064a7dbdefd97f0ba6982c7aaaefe breaks legacy branches / build that still bootstrap with old uid / gid while using up-to-date container images.

**Comment by h5b** [comment]
@TripleTrable @offa i'm happy to discuss the issue at hands.

**Comment by TripleTrable** [comment]
what you mean is the combination of, for example, the MS18 branch with a fedora 36 container as F36 and onward use the new uid/gid. Is that correct?

**Comment by TripleTrable** [comment]
isn't the fix simply to cherry pick 8b70fee62c2064a7dbdefd97f0ba6982c7aaaefe onto the affected branches?
Anything that uses F34 and below is unaffected because these containers aren't build anymore with the new config and anything above needs the mentioned commit.

**Comment by h5b** [comment]
Fixed
