### ISSUE TITLE
Switch main to default to scarthgap

### ISSUE THREAD

**Issue by h5b** [jhnc-oss/yocto-build#63]
Future LTS release poky/scarthgap will be available in April/2024 and supported until 2028 (4 years). Default should match latest LTS release.

**Comment by offa** [comment]
Should `main` become *scarthgap*  then too?

**Comment by h5b** [comment]
Has been released https://lists.yoctoproject.org/g/yocto-announce/message/311

**Comment by h5b** [comment]
Scarthgap branch has been made available and has been tested. Therefore, i suggest to update main to scarthgap and default to scarthgap for syncing (automatically) to main from now on.
